baseurl = "http://yourSiteHere"
languageCode = "it-IT"
title = "Game Coders"
Paginate = 5
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  featured = "featured"
[params]
  author = "Sebastian Faltoni"
